name: XML lint

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install xmllint

      - name: XML lint
        run: xmllint --schema ${{github.workspace}}/xml/lncvmodule.xsd --noout ${{github.workspace}}/xml/*.xml
